[FEATURE] Added table pokemons
svyatoslavvdovichenko/pokemons pull request #1
Opened 2022-12-30 09:37 UTC by svyatoslavvdovichenko

2022-12-30 10:22 UTC, anrekov commented on src/App.tsx
> +const App: FC = () => {
Это стрелочная функция, можно сократить запись (проверь не только здесь, но и в других файлах)

2022-12-30 10:23 UTC, anrekov commented on src/components/Pagination/Pagination.tsx
> +      </IconButton>
Разделяй, пожалуйста, элементы одного уровня вложенности пустой строкой. Для лучшей читаемости

2022-12-30 10:24 UTC, anrekov commented on src/components/Pokemons/Pokemons.tsx
> +        return pokemon.types
можно сократить запись

2022-12-30 10:28 UTC, anrekov commented on src/helper.ts
> +export const findColor = (types: string): "default" | "error" | "primary" | "secondary" | "info" | "success" | "warning" | undefined => {
types - скорее type
из-за `(types: string)` нужно `color!.color;`
пропиши типы точнее, пж (их, по идее, можно сформировать исходя из **chip**)

2022-12-30 10:28 UTC, anrekov commented on src/helper.ts
> +export const findVariant = (types: string): "outlined" | "filled" | undefined => {
аналогично

2022-12-30 10:29 UTC, anrekov commented on src/helper.ts
> +export const findColor = (types: string): "default" | "error" | "primary" | "secondary" | "info" | "success" | "warning" | undefined => {
export const commentsTabs = [
  'В работе',
  'Отправленные в ПИ',
  'Отклонённые',
  'Отработанные',
] as const;

export type TCommentsTab = typeof commentsTabs[number];

2023-01-10 13:16 UTC, anrekov commented on src/Page/Pokemon/Pokemon.tsx
> +  isGame: boolean;
$isGame
лучше так именовать пропы, которые чисто для стилей

2023-01-10 13:18 UTC, anrekov commented on src/Page/Pokemon/Pokemon.tsx
> +      console.log(`Just don't tell anyone his name: ${pokemon.name}`);
Why?)

2023-01-10 13:21 UTC, anrekov commented on src/Page/Pokemon/Pokemon.tsx
> +          sx={{ color: "#fff", zIndex: (theme) => theme.zIndex.drawer + 1 }}
can you use color from theme or global colors constant?

2023-01-10 13:24 UTC, anrekov commented on src/components/Pokemon/Tabs/PokeAbility.tsx
> +      setExpanded(isExpanded ? panel : false);
`      setExpanded(isExpanded && panel);`
This should work as well

2023-01-10 13:28 UTC, anrekov commented on src/store/pokemons/actionCreators.ts
> +      console.log(1);
do you need it?

2023-01-10 18:03 UTC, balakleeva requested changes
В целом лукс гуд, надо поработать с запросами
И также обязательно нужно добавить prettier. Но уже следующим коммитом, чтобы не было 100500 изменений

2023-01-10 18:03 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
> +      }
это будет работать неверно. `for` это не асинхронный оператор. тут нужно использовать Promise.all
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2023-01-10 18:03 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
> +        }>(response.data.abilities[index].ability.url);
тоже самое

2023-01-10 18:03 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
> +      }
тут тоже сложный promise.all

2023-03-03 13:20 UTC, merged

2023-03-05 12:23 UTC, balakleeva commented on src/components/SelectType/index.tsx
> +      <InputLabel id="demo-multiple-chip-label">Pokemon types</InputLabel>
нужен этот id?

2023-03-05 12:23 UTC, balakleeva commented on src/components/SelectType/index.tsx
> +  personName: string[] | null;
раз это массив, то именовать надо хотя бы personNames

2023-03-05 12:23 UTC, balakleeva commented on src/Page/Pokemons/Pokemons.tsx
> +                  qs.parse(searchParams.get('types') ?? ''),
а может тогда тут сделать так
```
qs.parse(searchParams.get('types') ?? [])
```

и тогда тебе не нужна будет проверка
```
setPersonName(typeof value === 'string' ? [value] : value);
```
в компоненте `MultipleSelectChip`

2023-03-05 12:23 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
> +      });
давай использовать map

2023-03-05 12:23 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
>            );
Promise.all

2023-03-05 12:23 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
> +        });
Promise.all

2023-03-05 12:23 UTC, balakleeva commented on src/store/pokemons/actionCreators.ts
> +        .catch(err => console.log('err', err));
надо добавить алерты на ошибки